name: ognigenoma
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.20
  - bedtools=2.31.1
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.7.4
  - gfatools=0.5
  - gsl=2.7
  - hifiasm=0.19.9
  - hmmer=3.4
  - htslib=1.20
  - intervaltree=3.1.0
  - irissv=1.0.5
  - jasminesv=1.1.5
  - k8=0.2.5
  - krb5=1.21.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libcxx=18.1.8
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libzlib=1.2.13
  - llvm-openmp=18.1.8
  - minigraph=0.21
  - minimap2=2.28
  - miniprot=0.13
  - mummer=3.23
  - ncurses=6.5
  - networkx=3.3
  - numpy=2.0.0
  - openjdk=22.0.1
  - openssl=3.3.1
  - perl=5.32.1
  - pip=24.0
  - pysam=0.22.1
  - python=3.12.3
  - python_abi=3.12
  - racon=1.5.0
  - ragtag=2.1.0
  - readline=8.2
  - rust-mdbg=1.0.1
  - samtools=1.20
  - setuptools=70.2.0
  - sniffles=2.3.2
  - sortedcontainers=2.4.0
  - tk=8.6.13
  - wheel=0.43.0
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - contourpy==1.2.1
      - cycler==0.12.1
      - fonttools==4.53.0
      - kiwisolver==1.4.5
      - matplotlib==3.9.0
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.3.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - six==1.16.0
      - tzdata==2024.1
      - upsetplot==0.9.0
